### ISSUE TITLE
WezTerm plugin support

### ISSUE THREAD

**Issue by raindev** [neapsix/wezterm#1]
Since recently WezTerm has basic plugin support (not yet documented):
https://github.com/wez/wezterm/commit/e4ae8a844d8feaa43e1de34c5cc8b4f07ce525dd

Plugins are expected to conform to a conventional structure, namely have `plugin/init.lua`. Here're some example plugins:
https://github.com/topics/wezterm-plugin

Would you be interested in adapting the theme structure to be usable as a plugin? Be usable as a plugin will make the theme easier to install from a configuration without having to manually copy the files.

Here's an example of how it could look like (I haven't figured out the way to load additional files and moved everything into `init.lua`):
https://github.com/raindev/rose-pine-wezterm/commit/89dd3a6b6bb724ca52e1ada09d0bedb18dadab14
Here's is an example usage:
https://github.com/raindev/dotfiles/blob/62f240947028a288f10d3dacc027a4e4bab27c26/dot_wezterm.lua.tmpl#L4-L14

Please let me know what do you think, I'd be happy to put together a PR.

---

Thanks a lot for sharing the theme! It's very nice to be able to also theme the tab bar as well.

**Comment by neapsix** [comment]
Hey! This looks great. And thanks so much for providing the background info! I agree—it'd be terrific if we could install the theme without manually copying files. 

Please do open a PR once you have a branch that you're happy with! It might be a couple weeks before I can take a look, but I'm cool with the change and would love to get it merged. 🙂

**Comment by raindev** [comment]
Hey! Thanks for the feedback!

I've did a bit of research on loading multiple plugin modules. While technically it's possible to achieve, the additional complexity (modifying package path or discovering the additional file on the filesystem) is probably not worth it for a theme. Hence I've opened a PR which merges the theme modules into one.
